
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 94
#define YY_END_OF_BUFFER 95
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[253] =
    {   0,
        0,    0,   95,   94,    3,   61,   94,   91,   63,   56,
       94,   48,   49,   57,   58,   90,   59,   52,   62,   41,
       41,   77,   78,   66,   80,   67,   76,   45,   46,   47,
       72,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   50,   92,   51,
       60,   71,    0,    0,   93,   83,   74,   88,    0,    0,
       81,   54,   84,   55,   85,   53,    0,   42,    2,    1,
       82,   42,    0,    0,   41,   64,   68,   70,   69,   65,
        0,   45,   89,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   11,   45,   45,   45,   45,   45,   45,   19,

       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   73,   75,   44,   79,    0,    1,    0,   43,   86,
       87,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   17,   45,   45,   21,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,    0,   43,   45,   45,
        4,   38,   45,    6,    7,   45,   45,   45,   45,   13,
       14,   45,   45,   18,   45,   22,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   35,   45,
       45,   45,   45,    5,    8,   45,   45,   45,   45,   16,

       45,   45,   45,   45,   26,   45,   45,   45,   45,   45,
       45,   33,   45,   45,   37,   45,   45,   45,   45,   12,
       15,   20,   45,   45,   25,   27,   28,   29,   30,   31,
       45,   45,   45,   45,   45,   45,   10,   45,   45,   32,
       45,   45,   39,   45,    9,   23,   24,   34,   36,   45,
       40,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    2,    3,    4,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    1,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   28,   29,   28,   30,   28,
       28,   28,   31,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       32,   33,   34,   35,   36,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   28,   46,   47,   48,   49,
       50,   51,   28,   52,   53,   54,   55,   56,   57,   58,
       59,   60,   61,   62,   63,   64,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[65] =
    {   0,
        1,    1,    1,    2,    1,    1,    1,    1,    1,    1,
        3,    1,    1,    1,    1,    1,    1,    1,    1,    4,
        4,    1,    1,    1,    1,    1,    1,    5,    5,    5,
        5,    1,    1,    1,    1,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        1,    1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[258] =
    {   0,
        0,    0,  153,  791,  791,  123,   63,  791,  109,   57,
       66,  791,  791,  106,   56,  791,   58,   58,   66,   68,
       74,  791,  791,   72,   94,   74,  791,   81,  791,  791,
       88,   85,   87,   91,  100,   97,  102,  105,  107,  112,
      109,  115,  119,  125,  145,  147,  149,  791,   62,  791,
      791,  791,  172,  175,  791,  791,  791,  791,  178,  185,
      791,  791,  791,  791,  791,  791,   92,  170,  791,    0,
      791,  183,  188,  199,  205,   78,  791,  791,  791,   52,
        0,  151,  791,  201,  207,  210,  212,  216,  218,  221,
      223,  227,  229,  232,  239,  245,  247,  253,  255,  257,

      259,  261,  268,  266,  271,  275,  280,  282,  287,  297,
      303,  791,  791,  791,  791,  326,    0,  299,  308,  791,
      791,  314,  316,  318,  329,  331,  333,  336,  338,  340,
      345,  342,  347,  351,  354,  363,  365,  371,  377,  381,
      383,  385,  387,  389,  391,  393,  395,  397,  399,  403,
      407,  411,  413,  419,  425,  417,  429,  432,  435,  445,
      447,  449,  451,  453,  455,  457,  459,  461,  463,  469,
      471,  473,  475,  478,  481,  485,  487,  492,  494,  497,
      500,  502,  511,  506,  514,  517,  522,  527,  529,  534,
      538,  540,  544,  542,  546,  548,  552,  554,  556,  560,

      562,  564,  570,  572,  580,  586,  588,  590,  592,  596,
      602,  599,  604,  607,  611,  613,  615,  617,  621,  624,
      627,  629,  635,  638,  640,  642,  645,  647,  649,  653,
      658,  660,  662,  664,  666,  669,  671,  673,  675,  677,
      684,  686,  691,  693,  695,  697,  699,  710,  712,  714,
      716,  791,  773,  778,  780,  785,   67
    } ;

static yyconst flex_int16_t yy_def[258] =
    {   0,
      252,    1,  252,  252,  252,  252,  253,  252,  252,  252,
      254,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  255,  252,  252,
      252,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  252,  252,  252,
      252,  252,  253,  253,  252,  252,  252,  252,  254,  254,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  256,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      257,  255,  252,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,

      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  252,  252,  252,  252,  252,  256,  252,  252,  252,
      252,  252,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  252,  252,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,

      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,    0,  252,  252,  252,  252,  252
    } ;

static yyconst flex_uint16_t yy_nxt[856] =
    {   0,
        4,    4,    5,    5,    5,    6,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   28,   28,
       28,   29,    4,   30,   31,   32,   33,   34,   35,   36,
       37,   38,   39,   28,   40,   28,   41,   28,   28,   28,
       28,   42,   43,   44,   45,   46,   47,   28,   28,   28,
       48,   49,   50,   51,   54,   54,   57,   60,   60,   55,
       62,  122,   60,   54,   64,   67,  121,   68,   68,   69,
       63,   58,   65,   66,   70,   72,  112,   73,   73,   54,
       71,   72,   60,   75,   75,   76,   77,   74,   79,   80,

       81,   81,  120,   74,   81,   81,   81,   81,   74,  115,
       81,   81,   83,   84,   74,   85,   81,   81,   78,   81,
       81,   81,   81,  113,   81,   81,   81,   81,   81,   81,
       61,   81,   81,   56,   81,   81,   89,   92,   81,   81,
       87,   86,   88,   90,   81,   81,   93,   52,   94,   91,
       95,   97,  252,  100,   98,  103,   99,  252,  102,   96,
      101,  252,  104,  105,   81,   81,   81,   81,   81,   81,
       81,   81,  106,   54,   54,  107,   54,   54,   55,   60,
       60,   55,   54,  108,   60,   54,   60,   60,  114,   68,
       68,   60,  111,  109,  252,  114,  110,  252,   54,  116,

      252,   54,   68,   68,   60,   72,  252,   73,   73,  252,
      116,   60,  116,  118,  252,  118,  252,   74,  119,  119,
       81,   81,   72,  116,   75,   75,   81,   81,   74,   81,
       81,   81,   81,  252,   74,   81,   81,   81,   81,  252,
       81,   81,   81,   81,  252,   74,   81,   81,   81,   81,
      123,   81,   81,  252,  124,  252,  127,  129,   81,   81,
      252,  126,  252,  125,   81,   81,   81,   81,  131,  252,
      128,  130,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,  252,  132,  133,   81,   81,   81,   81,  252,
       81,   81,  252,  134,   81,   81,  136,  252,  135,   81,

       81,   81,   81,  252,  137,  139,   81,   81,  138,  141,
      142,  148,  140,  146,  252,  145,   81,   81,  119,  119,
      143,  144,   81,   81,  150,  252,  149,  119,  119,  252,
      147,  152,  151,   81,   81,   81,   81,   81,   81,  153,
      157,  154,  157,  155,  252,  158,  158,  156,   81,   81,
       81,   81,   81,   81,  160,   81,   81,   81,   81,   81,
       81,   81,   81,  159,   81,   81,   81,   81,  252,  163,
       81,   81,  252,   81,   81,  252,  164,  162,  161,  169,
      252,  168,   81,   81,   81,   81,  252,  170,  252,  165,
       81,   81,  166,  167,  172,  252,   81,   81,  171,  173,

       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,
      174,  175,   81,   81,  252,  176,   81,   81,  252,  177,
       81,   81,   81,   81,  252,  182,   81,   81,   81,   81,
      178,  181,  180,  179,   81,   81,  252,  186,  158,  158,
      183,  158,  158,  184,   81,   81,  185,  188,  189,  252,
      187,  190,  252,  191,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,  252,  192,  252,  193,   81,   81,
       81,   81,   81,   81,   81,   81,  194,   81,   81,  252,

       81,   81,  252,  196,   81,   81,   81,   81,  252,  198,
      195,   81,   81,   81,   81,  197,   81,   81,  252,   81,
       81,   81,   81,  252,  199,   81,   81,  252,  200,  201,
       81,   81,  252,   81,   81,  252,   81,   81,  252,  202,
      206,   81,   81,  203,  209,  204,   81,   81,   81,   81,
      205,  207,  210,   81,   81,  208,  211,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   81,  213,
      212,   81,   81,   81,   81,   81,   81,  252,  215,   81,
       81,   81,   81,   81,   81,  252,  216,  214,  217,   81,
       81,   81,   81,  252,  220,  252,  218,  252,  219,   81,

       81,  252,  222,  252,  221,   81,   81,   81,   81,   81,
       81,   81,   81,  252,  224,   81,   81,  223,   81,   81,
      225,   81,   81,   81,   81,  226,   81,   81,  228,  227,
       81,   81,   81,   81,   81,   81,   81,   81,  252,  230,
       81,   81,  231,   81,   81,  229,   81,   81,   81,   81,
      252,  233,  232,  234,   81,   81,  252,   81,   81,   81,
       81,   81,   81,  235,   81,   81,   81,   81,   81,   81,
      252,  236,   81,   81,  237,  238,  239,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,  252,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,  252,  240,

      241,  252,  244,   81,   81,   81,   81,  252,  242,  245,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,
      252,  243,  252,  248,  246,  252,  249,  252,  247,   81,
       81,   81,   81,   81,   81,   81,   81,  252,  252,  252,
      252,  252,  252,  252,  250,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  251,   53,  252,   53,   53,   53,   59,  252,
      252,   59,   59,   82,   82,  117,  252,  117,  117,  117,
        3,  252,  252,  252,  252,  252,  252,  252,  252,  252,

      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252
    } ;

static yyconst flex_int16_t yy_chk[856] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    7,    7,   10,   11,   11,    7,
       15,  257,   11,    7,   17,   18,   80,   18,   18,   19,
       15,   10,   17,   17,   19,   20,   49,   20,   20,    7,
       19,   21,   11,   21,   21,   24,   24,   20,   26,   26,

       28,   28,   76,   21,   32,   32,   33,   33,   20,   67,
       34,   34,   31,   32,   21,   32,   36,   36,   25,   35,
       35,   37,   37,   49,   38,   38,   39,   39,   41,   41,
       14,   40,   40,    9,   42,   42,   35,   36,   43,   43,
       34,   33,   34,   35,   44,   44,   36,    6,   37,   35,
       37,   38,    3,   40,   38,   42,   39,    0,   41,   37,
       40,    0,   43,   43,   45,   45,   46,   46,   47,   47,
       82,   82,   43,   53,   53,   43,   54,   54,   53,   59,
       59,   54,   53,   44,   59,   54,   60,   60,   59,   68,
       68,   60,   47,   45,    0,   60,   46,    0,   53,   68,

        0,   54,   72,   72,   59,   73,    0,   73,   73,    0,
       68,   60,   72,   74,    0,   74,    0,   73,   74,   74,
       84,   84,   75,   72,   75,   75,   85,   85,   73,   86,
       86,   87,   87,    0,   75,   88,   88,   89,   89,    0,
       90,   90,   91,   91,    0,   75,   92,   92,   93,   93,
       84,   94,   94,    0,   85,    0,   88,   90,   95,   95,
        0,   87,    0,   86,   96,   96,   97,   97,   92,    0,
       89,   91,   98,   98,   99,   99,  100,  100,  101,  101,
      102,  102,    0,   93,   94,  104,  104,  103,  103,    0,
      105,  105,    0,   95,  106,  106,   97,    0,   96,  107,

      107,  108,  108,    0,   98,  101,  109,  109,   99,  102,
      103,  106,  101,  105,    0,  104,  110,  110,  118,  118,
      103,  103,  111,  111,  107,    0,  106,  119,  119,    0,
      105,  109,  108,  122,  122,  123,  123,  124,  124,  109,
      116,  110,  116,  110,    0,  116,  116,  111,  125,  125,
      126,  126,  127,  127,  124,  128,  128,  129,  129,  130,
      130,  132,  132,  123,  131,  131,  133,  133,    0,  127,
      134,  134,    0,  135,  135,    0,  128,  126,  125,  132,
        0,  131,  136,  136,  137,  137,    0,  133,    0,  129,
      138,  138,  130,  130,  135,    0,  139,  139,  134,  136,

      140,  140,  141,  141,  142,  142,  143,  143,  144,  144,
      145,  145,  146,  146,  147,  147,  148,  148,  149,  149,
      138,  139,  150,  150,    0,  141,  151,  151,    0,  142,
      152,  152,  153,  153,    0,  147,  156,  156,  154,  154,
      143,  146,  145,  144,  155,  155,    0,  151,  157,  157,
      148,  158,  158,  149,  159,  159,  150,  153,  154,    0,
      152,  155,    0,  156,  160,  160,  161,  161,  162,  162,
      163,  163,  164,  164,  165,  165,  166,  166,  167,  167,
      168,  168,  169,  169,    0,  159,    0,  160,  170,  170,
      171,  171,  172,  172,  173,  173,  163,  174,  174,    0,

      175,  175,    0,  167,  176,  176,  177,  177,    0,  169,
      166,  178,  178,  179,  179,  168,  180,  180,    0,  181,
      181,  182,  182,    0,  172,  184,  184,    0,  173,  175,
      183,  183,    0,  185,  185,    0,  186,  186,    0,  177,
      181,  187,  187,  178,  184,  179,  188,  188,  189,  189,
      180,  182,  185,  190,  190,  183,  186,  191,  191,  192,
      192,  194,  194,  193,  193,  195,  195,  196,  196,  188,
      187,  197,  197,  198,  198,  199,  199,    0,  191,  200,
      200,  201,  201,  202,  202,    0,  192,  190,  193,  203,
      203,  204,  204,    0,  198,    0,  196,    0,  197,  205,

      205,    0,  201,    0,  199,  206,  206,  207,  207,  208,
      208,  209,  209,    0,  203,  210,  210,  202,  212,  212,
      204,  211,  211,  213,  213,  206,  214,  214,  208,  207,
      215,  215,  216,  216,  217,  217,  218,  218,    0,  210,
      219,  219,  211,  220,  220,  209,  221,  221,  222,  222,
        0,  214,  213,  216,  223,  223,    0,  224,  224,  225,
      225,  226,  226,  217,  227,  227,  228,  228,  229,  229,
        0,  218,  230,  230,  219,  223,  224,  231,  231,  232,
      232,  233,  233,  234,  234,  235,  235,    0,  236,  236,
      237,  237,  238,  238,  239,  239,  240,  240,    0,  231,

      232,    0,  235,  241,  241,  242,  242,    0,  233,  236,
      243,  243,  244,  244,  245,  245,  246,  246,  247,  247,
        0,  234,    0,  241,  238,    0,  242,    0,  239,  248,
      248,  249,  249,  250,  250,  251,  251,    0,    0,    0,
        0,    0,    0,    0,  244,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  250,  253,    0,  253,  253,  253,  254,    0,
        0,  254,  254,  255,  255,  256,    0,  256,  256,  256,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,

      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "ass5_17CS10007_17CS10005.l"
#line 2 "ass5_17CS10007_17CS10005.l"
  #include "ass5_17CS10007_17CS10005_translator.h"
  #include "y.tab.h"  
  extern void yyerror(char*);
  void comment();
#line 746 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 35 "ass5_17CS10007_17CS10005.l"


#line 967 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 253 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 791 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 37 "ass5_17CS10007_17CS10005.l"
{;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 38 "ass5_17CS10007_17CS10005.l"
{comment();}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 40 "ass5_17CS10007_17CS10005.l"
{;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 42 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("auto"); return AUTO;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 43 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("break"); return BREAK;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 44 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("case"); return CASE;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 45 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("char"); return CHAR;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 46 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("const"); return CONST;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 47 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("continue"); return CONTINUE;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 48 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("default"); return DEFAULT;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 49 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("do"); return DO;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 50 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("double"); return DOUBLE;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 51 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("else"); return ELSE;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 52 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("enum"); return ENUM;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 53 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("extern"); return EXTERN;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 54 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("float"); return FLOAT;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 55 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("for"); return FOR;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 56 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("goto"); return GOTO;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 57 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("if"); return IF;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 58 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("inline"); return INLINE;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 59 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("int"); return INT;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 60 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("long"); return LONG;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 61 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("register"); return REGISTER;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 62 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("restrict"); return RESTRICT;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 63 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("return"); return RETURN;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 64 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("short"); return SHORT;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 65 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("signed"); return SIGNED;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 66 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("sizeof"); return SIZEOF;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 67 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("static"); return STATIC;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 68 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("struct"); return STRUCT;}	
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 69 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("switch"); return SWITCH;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 70 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("typedef"); return TYPEDEF;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 71 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("union"); return UNION;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 72 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("unsigned"); return UNSIGNED;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 73 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("void"); return VOID;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 74 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("volatile"); return VOLATILE;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 75 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("while"); return WHILE;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 76 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("_Bool"); return _BOOL;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 77 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("_Complex"); return _COMPLEX;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 78 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("_Imaginary"); return _IMAGINARY;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 80 "ass5_17CS10007_17CS10005.l"
{yylval.intval=atoi(yytext); return INT_CONST;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 81 "ass5_17CS10007_17CS10005.l"
{sscanf(yytext, "%lf", &yylval.real);return FRACTION_CONST;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 82 "ass5_17CS10007_17CS10005.l"
{sscanf(yytext, "%lf", &yylval.real); return FLOAT_CONST;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 83 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup(yytext); return CHAR_CONST;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 85 "ass5_17CS10007_17CS10005.l"
{yylval.symnode=new SymNode;yylval.symnode->name=string(yytext); return IDENTIFIER;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 87 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("["); return L_SQRB;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 88 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("]"); return R_SQRB;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 89 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("("); return L_PARAN;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 90 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup(")"); return R_PARAN;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 91 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("{"); return L_BRACES;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 92 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("}"); return R_BRACES;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 93 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("."); return DOT;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 94 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("->"); return ARROW_ASSIGN;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 95 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("++"); return INCREMENT;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 96 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("--"); return DECREMENT;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 97 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("&"); return BIT_AND;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 98 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("*"); return MUL;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 99 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("+"); return ADD;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 100 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("-"); return MINUS;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 101 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("~"); return NEGATE;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 102 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("!"); return NOT;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 103 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("/"); return DIVIDE;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 104 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("%"); return REMAINDER;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 105 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("<<"); return L_SHIFT;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 106 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup(">>"); return R_SHIFT;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 107 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("<"); return LESS_THAN;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 108 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup(">"); return GREATER_THAN;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 109 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("<="); return LESS_THAN_EQUAL;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 110 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup(">="); return GREATER_THAN_EQUAL;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 111 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("=="); return IS_EQUAL;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 112 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("!="); return NOT_EQUAL;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 113 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("^"); return BIT_XOR;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 114 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("|="); return BIT_OR_ASSIGN;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 115 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("&&"); return BOOL_AND;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 116 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("||"); return BOOL_OR;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 117 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("?"); return QM;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 118 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup(":"); return COLON;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 119 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup(";"); return SEMICOLON;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 120 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("..."); return ELLIPSES;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 121 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("="); return ASSIGN;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 122 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("*="); return MUL_ASSIGN;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 123 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("/="); return DIVIDE_ASSIGN;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 124 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("%="); return REM_ASSIGN;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 125 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("+="); return ADD_ASSIGN;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 126 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("-="); return MINUS_ASSIGN;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 127 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("<<="); return L_SHIFT_ASSIGN;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 128 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup(">>="); return R_SHIFT_ASSIGN;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 129 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("&="); return BIT_AND_ASSIGN;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 130 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("^="); return BIT_XOR_ASSIGN;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 131 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup(","); return COMMA;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 132 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("#"); return HASH;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 133 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup("|"); return BIT_OR;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 134 "ass5_17CS10007_17CS10005.l"
{yylval.str=strdup(yytext); return STRING_LITERAL;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 136 "ass5_17CS10007_17CS10005.l"
ECHO;
	YY_BREAK
#line 1495 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 253 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 253 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 252);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 136 "ass5_17CS10007_17CS10005.l"



void comment(){
	char c, prev = 0;
	while ((c = yyinput()) != 0){
		if (c == '/' && prev == '*') return;
		prev = c;
	}
	char* temp=(char*)calloc(30,sizeof(char));
	strcpy(temp,"unterminated comment");
	yyerror(temp);
}


